force-app/main/default/objects/Contact/fields/Calendar_Access_Requests__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Access_Requests__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of calendar access requests sent to physician to share calendar with clinic&apos;s service account</description>
    <label>Calendar Access Requests?</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
                <default>true</default>
                <label>Female</label>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/OnDuty__c.field-meta.xml
<CustomField>
    <fullName>OnDuty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Duty?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specialization</label>
    <referenceTo>Specialization__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Physician.recordType-meta.xml
<RecordType>
    <fullName>Physician</fullName>
    <active>true</active>
    <label>Physician</label>
</RecordType>

force-app/main/default/objects/Specialization__c/Specialization__c.object-meta.xml
<CustomObject>
    <description>Contains specializations in clinic.</description>
    <label>Specialization</label>
    <nameField>
        <label>Specialization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specializations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Specialization__c/fields/Appointment_Price__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Price__c</fullName>
    <description>Price of appointment for specialization</description>
    <inlineHelpText>(in USD)</inlineHelpText>
    <label>Appointment Price(USD)</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/FillAppointmentDetailsController.cls
public class FillAppointmentDetailsController {
    
    @AuraEnabled(cacheable=true)
    public static List<Specialization__c> getSpecializations(){
        List<Specialization__c> listSpecializations=[Select Id, Name, Appointment_Price__c from Specialization__c];
        return listSpecializations;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Contact> getPhysiciansForSpecialization(String specId) {
        Id physicianRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Physician').getRecordTypeId();
        List<Contact> result = [
            SELECT Id, Name, Gender__c, Specialization__c, Phone, Email, Calendar_Access_Requests__c
            FROM Contact
            WHERE RecordTypeId =:physicianRecTypeId AND Specialization__c=:specId AND OnDuty__c=true
            WITH SECURITY_ENFORCED
        ];
        return result;
    }

    @AuraEnabled(cacheable=true)
    public static List<GoogleIntegrationUtility.CalendarItem> getAvailableSlots(String apiResponse, Date inpDate) {
        List<GoogleIntegrationUtility.CalendarItem> bookedAppointments = GoogleIntegrationUtility.parseCalendarEventResponse(apiResponse);
        List<GoogleIntegrationUtility.CalendarItem> openSlots = GoogleIntegrationUtility.createAvailableCalendarSlots(bookedAppointments, inpDate);        
        return openSlots;
    }

    @AuraEnabled
    public static Contact sendCalendarRequestAccess(Contact physician) {
        Contact physicianToUpdate;
        if(physician!=null && physician.Id!=null) {
            physicianToUpdate = new Contact(Id=physician.Id);
            physicianToUpdate.Calendar_Access_Requests__c = (physician.Calendar_Access_Requests__c!=null && physician.Calendar_Access_Requests__c > 0) ? (physician.Calendar_Access_Requests__c + 1) : 1 ;
            update physicianToUpdate;
        }
        return physicianToUpdate;
    }
}